"""
Curated Registry of 300+ Top Tech Sources, Public ATS Endpoints & Tech Feeds.
Includes Top 500 Tech Giants, Tier-1 AI Unicorns, DevTool Leaders, Internshala, and Tech Aggregators.
"""

# 1. Internshala Direct Paid Internship Feeds (20 Specialized CS & Engineering Streams)
INTERNSHALA_URLS = [
    "https://internshala.com/internships/work-from-home-computer-science-internships/",
    "https://internshala.com/internships/computer-science-internship/",
    "https://internshala.com/internships/web-development-internship/",
    "https://internshala.com/internships/python-django-internship/",
    "https://internshala.com/internships/java-internship/",
    "https://internshala.com/internships/artificial-intelligence-ai-internship/",
    "https://internshala.com/internships/data-science-internship/",
    "https://internshala.com/internships/information-technology-internship/",
    "https://internshala.com/internships/front-end-development-internship/",
    "https://internshala.com/internships/backend-development-internship/",
    "https://internshala.com/internships/full-stack-development-internship/",
    "https://internshala.com/internships/mobile-app-development-internship/",
    "https://internshala.com/internships/android-app-development-internship/",
    "https://internshala.com/internships/flutter-development-internship/",
    "https://internshala.com/internships/reactjs-development-internship/",
    "https://internshala.com/internships/node-js-development-internship/",
    "https://internshala.com/internships/cloud-computing-internship/",
    "https://internshala.com/internships/devops-internship/",
    "https://internshala.com/internships/cyber-security-internship/",
    "https://internshala.com/internships/machine-learning-internship/"
]

# 2. Ashby HQ Public API Targets (105 Tier-1 AI Unicorns, Developer Tooling & Startups)
ASHBY_SOURCES = [
    {"name": "Linear", "slug": "linear", "category": "Dev Tools"},
    {"name": "Perplexity AI", "slug": "perplexity", "category": "AI / Search"},
    {"name": "Cursor / Anysphere", "slug": "cursor", "category": "AI / IDE"},
    {"name": "Replit", "slug": "replit", "category": "Cloud / IDE"},
    {"name": "Ramp", "slug": "ramp", "category": "Fintech"},
    {"name": "PostHog", "slug": "posthog", "category": "Product Analytics"},
    {"name": "Together AI", "slug": "togetherai", "category": "AI / Cloud"},
    {"name": "Elicit", "slug": "elicit", "category": "AI / Research"},
    {"name": "Vercel", "slug": "vercel", "category": "Frontend Cloud"},
    {"name": "Mistral AI", "slug": "mistralai", "category": "AI / LLM"},
    {"name": "Brex", "slug": "brex", "category": "Fintech"},
    {"name": "Deel", "slug": "deel", "category": "Global HR / Fintech"},
    {"name": "Rippling", "slug": "rippling", "category": "Enterprise SaaS"},
    {"name": "Retool", "slug": "retool", "category": "Internal Tools"},
    {"name": "ElevenLabs", "slug": "elevenlabs", "category": "AI / Voice"},
    {"name": "Groq", "slug": "groq", "category": "AI Hardware / Cloud"},
    {"name": "Weights & Biases", "slug": "weightsandbiases", "category": "MLOps"},
    {"name": "Modal", "slug": "modal", "category": "Serverless AI"},
    {"name": "LangChain", "slug": "langchain", "category": "AI Frameworks"},
    {"name": "Pinecone", "slug": "pinecone", "category": "Vector DB"},
    {"name": "Runway", "slug": "runwayml", "category": "AI Video"},
    {"name": "Stability AI", "slug": "stabilityai", "category": "GenAI"},
    {"name": "Jasper AI", "slug": "jasper", "category": "GenAI"},
    {"name": "Character AI", "slug": "characterai", "category": "Conversational AI"},
    {"name": "Sierra AI", "slug": "sierra", "category": "Enterprise AI"},
    {"name": "Synthesia", "slug": "synthesia", "category": "AI Video"},
    {"name": "Harvey AI", "slug": "harvey", "category": "Legal AI"},
    {"name": "Glean", "slug": "glean", "category": "Enterprise Search"},
    {"name": "Writer", "slug": "writer", "category": "Enterprise GenAI"},
    {"name": "Lovable", "slug": "lovable", "category": "Fullstack AI"},
    {"name": "Supabase", "slug": "supabase", "category": "Open Source Backend"},
    {"name": "Inkeep", "slug": "inkeep", "category": "AI Support"},
    {"name": "Mintlify", "slug": "mintlify", "category": "Developer Docs"},
    {"name": "Raycast", "slug": "raycast", "category": "Productivity Tools"},
    {"name": "Vapi", "slug": "vapi", "category": "Voice AI"},
    {"name": "Prisma", "slug": "prisma", "category": "Database ORM"},
    {"name": "Cal.com", "slug": "cal.com", "category": "Open Source Scheduling"},
    {"name": "Dub.co", "slug": "dub", "category": "Open Source Link Mgmt"},
    {"name": "GitBook", "slug": "gitbook", "category": "Developer Knowledge"},
    {"name": "Railway", "slug": "railway", "category": "Cloud Infrastructure"},
    {"name": "Helicone", "slug": "helicone", "category": "LLM Observability"},
    {"name": "Render", "slug": "render", "category": "Cloud Hosting"},
    {"name": "Chroma", "slug": "chroma", "category": "AI Vector DB"},
    {"name": "Weaviate", "slug": "weaviate", "category": "AI Vector Search"},
    {"name": "Qdrant", "slug": "qdrant", "category": "Vector Search Engine"},
    {"name": "LlamaIndex", "slug": "llamaindex", "category": "Data Framework for LLMs"},
    {"name": "Midjourney", "slug": "midjourney", "category": "GenAI Image"},
    {"name": "Phind", "slug": "phind", "category": "AI Search for Developers"},
    {"name": "Deepgram", "slug": "deepgram", "category": "Speech-to-Text AI"},
    {"name": "Speakeasy", "slug": "speakeasy", "category": "SDK Generation"},
    {"name": "Unify", "slug": "unify", "category": "LLM Router"},
    {"name": "Pydantic", "slug": "pydantic", "category": "Data Validation"},
    {"name": "Hex", "slug": "hex", "category": "Collaborative Analytics"},
    {"name": "MotherDuck", "slug": "motherduck", "category": "Serverless DuckDB"},
    {"name": "Tinybird", "slug": "tinybird", "category": "Realtime Data API"},
    {"name": "Neon", "slug": "neon", "category": "Serverless Postgres"},
    {"name": "Upstash", "slug": "upstash", "category": "Serverless Redis & Kafka"},
    {"name": "Turso", "slug": "turso", "category": "Serverless LibSQL"},
    {"name": "Meilisearch", "slug": "meilisearch", "category": "Fast Search Engine"},
    {"name": "Typesense", "slug": "typesense", "category": "Open Source Search"},
    {"name": "Appwrite", "slug": "appwrite", "category": "BaaS Platform"},
    {"name": "Directus", "slug": "directus", "category": "Backend & Data Studio"},
    {"name": "Strapi", "slug": "strapi", "category": "Headless CMS"},
    {"name": "Novu", "slug": "novu", "category": "Notification Infrastructure"},
    {"name": "Medusa", "slug": "medusajs", "category": "Commerce Platform"},
    {"name": "Payload CMS", "slug": "payloadcms", "category": "Fullstack Typescript CMS"},
    {"name": "Astro", "slug": "astro", "category": "Web Framework"},
    {"name": "Deno", "slug": "deno", "category": "Next-gen JS Runtime"},
    {"name": "Bun", "slug": "bun", "category": "Fast All-in-one JS Runtime"},
    {"name": "Expo", "slug": "expo", "category": "React Native Platform"},
    {"name": "Svix", "slug": "svix", "category": "Webhooks Infrastructure"},
    {"name": "Knock", "slug": "knock", "category": "Notifications Infrastructure"},
    {"name": "Trigger.dev", "slug": "triggerdev", "category": "Background Jobs Platform"},
    {"name": "Inngest", "slug": "inngest", "category": "Event-Driven Orchestration"},
    {"name": "Hatchet", "slug": "hatchet", "category": "Distributed Workflows"},
    {"name": "Temporal", "slug": "temporal", "category": "Resilient Execution"},
    {"name": "Prefect", "slug": "prefect", "category": "Data Workflow Engine"},
    {"name": "Dagster", "slug": "dagster", "category": "Data Orchestration"},
    {"name": "Airbyte", "slug": "airbyte", "category": "Data Integration"},
    {"name": "Meltano", "slug": "meltano", "category": "DataOps Platform"},
    {"name": "Cube", "slug": "cube", "category": "Universal Semantic Layer"},
    {"name": "Metabase", "slug": "metabase", "category": "Open Source BI"},
    {"name": "Preset", "slug": "preset", "category": "Modern Cloud Analytics"},
    {"name": "Streamlit", "slug": "streamlit", "category": "Data App Framework"},
    {"name": "Braintrust", "slug": "braintrust", "category": "AI Evaluation Platform"},
    {"name": "Resend", "slug": "resend", "category": "Email API for Developers"},
    {"name": "Decart", "slug": "decart", "category": "AI Realtime Worlds"},
    {"name": "Together", "slug": "together", "category": "AI Cloud"},
    {"name": "Cohere", "slug": "cohere", "category": "Enterprise AI"},
    {"name": "Fireworks AI", "slug": "fireworks", "category": "Fast AI Inference"},
    {"name": "Livepeer", "slug": "livepeer", "category": "Decentralized Video AI"},
    {"name": "Tamagui", "slug": "tamagui", "category": "UI Kit for React"},
    {"name": "FlutterFlow", "slug": "flutterflow", "category": "Visual App Builder"},
    {"name": "Zeplo", "slug": "zeplo", "category": "Serverless Queue API"},
    {"name": "Defer", "slug": "defer", "category": "Background Execution for Node"},
    {"name": "Evidence", "slug": "evidence", "category": "Code-based BI"},
    {"name": "NocoDB", "slug": "nocodb", "category": "Open Source Airtable"},
    {"name": "Baserow", "slug": "baserow", "category": "Open Source Database"},
    {"name": "Tauri", "slug": "tauri", "category": "Lightweight Desktop Framework"},
    {"name": "Elysia", "slug": "elysia", "category": "Fast Bun Web Framework"},
    {"name": "Remix", "slug": "remix", "category": "Fullstack Web Framework"},
    {"name": "Supaglue", "slug": "supaglue", "category": "Open Source Integrations"},
    {"name": "DuckDB Labs", "slug": "duckdblabs", "category": "High-Performance Analytics"},
    {"name": "Speakeasy API", "slug": "speakeasyapi", "category": "Developer Experience Platform"}
]

# 3. Greenhouse Public API Targets (140 Top Tech Companies, Unicorns & Global Employers)
GREENHOUSE_SOURCES = [
    {"name": "Stripe", "slug": "stripe", "category": "Fintech Infrastructure"},
    {"name": "OpenAI", "slug": "openai", "category": "AI Research & Systems"},
    {"name": "Anthropic", "slug": "anthropic", "category": "AI Safety & LLMs"},
    {"name": "Scale AI", "slug": "scaleai", "category": "Data & AI Infrastructure"},
    {"name": "Databricks", "slug": "databricks", "category": "Data & AI Platform"},
    {"name": "Snowflake", "slug": "snowflake", "category": "Cloud Data Platform"},
    {"name": "Cloudflare", "slug": "cloudflare", "category": "Global Edge Network"},
    {"name": "Figma", "slug": "figma", "category": "Design & Collaboration"},
    {"name": "MongoDB", "slug": "mongodb", "category": "Modern Database Platform"},
    {"name": "Datadog", "slug": "datadog", "category": "Observability & Security"},
    {"name": "Elastic", "slug": "elastic", "category": "Search & Analytics"},
    {"name": "GitLab", "slug": "gitlab", "category": "DevSecOps Platform"},
    {"name": "Coinbase", "slug": "coinbase", "category": "Crypto & Web3"},
    {"name": "Robinhood", "slug": "robinhood", "category": "Fintech & Trading"},
    {"name": "Discord", "slug": "discord", "category": "Communications & Community"},
    {"name": "Pinterest", "slug": "pinterest", "category": "Visual Discovery"},
    {"name": "Airtable", "slug": "airtable", "category": "Low-Code Platform"},
    {"name": "Twilio", "slug": "twilio", "category": "Cloud Communications"},
    {"name": "Grafana Labs", "slug": "grafanalabs", "category": "Open Source Observability"},
    {"name": "PlanetScale", "slug": "planetscale", "category": "Serverless MySQL"},
    {"name": "Warp", "slug": "warp", "category": "Modern Terminal"},
    {"name": "ClickHouse", "slug": "clickhouse", "category": "Real-Time Columnar DB"},
    {"name": "Docker", "slug": "docker", "category": "Containerization"},
    {"name": "Temporal", "slug": "temporalio", "category": "Microservices Orchestration"},
    {"name": "Sentry", "slug": "sentry", "category": "Application Performance"},
    {"name": "Fly.io", "slug": "flyio", "category": "Global App Platform"},
    {"name": "Zapier", "slug": "zapier", "category": "Workflow Automation"},
    {"name": "Astronomer", "slug": "astronomer", "category": "Apache Airflow Cloud"},
    {"name": "Neon", "slug": "neon", "category": "Serverless Database"},
    {"name": "Cockroach Labs", "slug": "cockroachdb", "category": "Distributed SQL"},
    {"name": "Redis", "slug": "redis", "category": "In-Memory Data Store"},
    {"name": "Automattic", "slug": "automattic", "category": "WordPress & Open Web"},
    {"name": "Pulumi", "slug": "pulumi", "category": "Infrastructure as Code"},
    {"name": "Doppler", "slug": "doppler", "category": "SecretOps Platform"},
    {"name": "Zoom", "slug": "zoom", "category": "Video Communications"},
    {"name": "Kong", "slug": "kong", "category": "Cloud API Gateway"},
    {"name": "Notion", "slug": "notion", "category": "Workspace & Docs"},
    {"name": "DoorDash", "slug": "doordash", "category": "Logistics & Marketplace"},
    {"name": "Okta", "slug": "okta", "category": "Identity & Access Mgmt"},
    {"name": "Splunk", "slug": "splunk", "category": "Cybersecurity & Data"},
    {"name": "CrowdStrike", "slug": "crowdstrike", "category": "Cloud Security"},
    {"name": "SentinelOne", "slug": "sentinelone", "category": "Autonomous AI Security"},
    {"name": "Zscaler", "slug": "zscaler", "category": "Zero Trust Security"},
    {"name": "Palo Alto Networks", "slug": "paloaltonetworks", "category": "Cybersecurity"},
    {"name": "Fortinet", "slug": "fortinet", "category": "Network Security"},
    {"name": "Fastly", "slug": "fastly", "category": "Edge Cloud Network"},
    {"name": "Akamai", "slug": "akamai", "category": "Content Delivery & Security"},
    {"name": "SendGrid", "slug": "sendgrid", "category": "Email Delivery Cloud"},
    {"name": "Box", "slug": "box", "category": "Content Cloud"},
    {"name": "Dropbox", "slug": "dropbox", "category": "File Hosting & Sync"},
    {"name": "Asana", "slug": "asana", "category": "Work Management"},
    {"name": "Monday.com", "slug": "monday", "category": "Work OS"},
    {"name": "Coda", "slug": "coda", "category": "All-in-one Doc Platform"},
    {"name": "Miro", "slug": "miro", "category": "Visual Workspace"},
    {"name": "Lucid", "slug": "lucid", "category": "Visual Collaboration Suite"},
    {"name": "Canva", "slug": "canva", "category": "Visual Design Suite"},
    {"name": "Webflow", "slug": "webflow", "category": "Visual Web Development"},
    {"name": "Framer", "slug": "framer", "category": "Interactive Design & Web"},
    {"name": "Netlify", "slug": "netlify", "category": "Frontend Cloud & Serverless"},
    {"name": "DigitalOcean", "slug": "digitalocean", "category": "Developer Cloud"},
    {"name": "Linode", "slug": "linode", "category": "Cloud Computing Infrastructure"},
    {"name": "Hetzner", "slug": "hetzner", "category": "Dedicated & Cloud Hosting"},
    {"name": "Scaleway", "slug": "scaleway", "category": "European Cloud Provider"},
    {"name": "Fivetran", "slug": "fivetran", "category": "Automated Data Movement"},
    {"name": "dbt Labs", "slug": "dbtlabs", "category": "Data Transformation in SQL"},
    {"name": "Starburst", "slug": "starburst", "category": "Data Lakehouse Analytics"},
    {"name": "Dremio", "slug": "dremio", "category": "Data Lakehouse Engine"},
    {"name": "Imply", "slug": "imply", "category": "Real-time Apache Druid"},
    {"name": "SingleStore", "slug": "singlestore", "category": "High-Performance Distributed DB"},
    {"name": "Couchbase", "slug": "couchbase", "category": "NoSQL Cloud Database"},
    {"name": "Neo4j", "slug": "neo4j", "category": "Graph Database & Analytics"},
    {"name": "DataStax", "slug": "datastax", "category": "Generative AI Data Stack"},
    {"name": "ScyllaDB", "slug": "scylladb", "category": "Ultra-Fast NoSQL DB"},
    {"name": "Yugabyte", "slug": "yugabyte", "category": "Distributed SQL Database"},
    {"name": "Timescale", "slug": "timescale", "category": "Time-Series Postgres"},
    {"name": "QuestDB", "slug": "questdb", "category": "High-Speed Time Series DB"},
    {"name": "InfluxData", "slug": "influxdata", "category": "Time-Series Data Platform"},
    {"name": "VictoriaMetrics", "slug": "victoriametrics", "category": "Monitoring & TSDB"},
    {"name": "New Relic", "slug": "newrelic", "category": "Full-Stack Observability"},
    {"name": "Dynatrace", "slug": "dynatrace", "category": "AI-Powered Observability"},
    {"name": "AppDynamics", "slug": "appdynamics", "category": "Application Observability"},
    {"name": "Honeycomb", "slug": "honeycomb", "category": "High-Cardinality Observability"},
    {"name": "Lightstep", "slug": "lightstep", "category": "Distributed Tracing"},
    {"name": "Sumo Logic", "slug": "sumologic", "category": "Log Analytics & SIEM"},
    {"name": "Logz.io", "slug": "logzio", "category": "Open-Source Observability"},
    {"name": "Coralogix", "slug": "coralogix", "category": "Real-Time Streaming Analytics"},
    {"name": "Better Stack", "slug": "betterstack", "category": "Uptime & Log Management"},
    {"name": "HashiCorp", "slug": "hashicorp", "category": "Multi-Cloud Infrastructure"},
    {"name": "Confluent", "slug": "confluent", "category": "Apache Kafka Data Streaming"},
    {"name": "LaunchDarkly", "slug": "launchdarkly", "category": "Feature Management"},
    {"name": "Split", "slug": "split", "category": "Feature Flagging & Experimentation"},
    {"name": "Statsig", "slug": "statsig", "category": "Product Experimentation"},
    {"name": "Amplitude", "slug": "amplitude", "category": "Digital Analytics Platform"},
    {"name": "Mixpanel", "slug": "mixpanel", "category": "Event Analytics"},
    {"name": "Heap", "slug": "heap", "category": "Digital Insights & Analytics"},
    {"name": "Segment", "slug": "segment", "category": "Customer Data Platform"},
    {"name": "RudderStack", "slug": "rudderstack", "category": "Warehouse-Native CDP"},
    {"name": "Freshworks", "slug": "freshworks", "category": "SaaS Customer Software"},
    {"name": "Postman", "slug": "postman", "category": "API Development Platform"},
    {"name": "Insomnia", "slug": "insomnia", "category": "Open Source API Client"},
    {"name": "PostgreSQL", "slug": "postgresql", "category": "Relational Database"},
    {"name": "Kinsta", "slug": "kinsta", "category": "Managed Application Hosting"},
    {"name": "WP Engine", "slug": "wpengine", "category": "WordPress Cloud Hosting"},
    {"name": "CircleCI", "slug": "circleci", "category": "Continuous Integration & Delivery"},
    {"name": "Travis CI", "slug": "travisci", "category": "Cloud CI Service"},
    {"name": "Buildkite", "slug": "buildkite", "category": "Hybrid CI/CD Pipelines"},
    {"name": "Codecov", "slug": "codecov", "category": "Code Coverage Intelligence"},
    {"name": "Sonatype", "slug": "sonatype", "category": "Software Supply Chain Security"},
    {"name": "Snyk", "slug": "snyk", "category": "Developer Security Platform"},
    {"name": "Checkmarx", "slug": "checkmarx", "category": "Application Security Testing"},
    {"name": "Veracode", "slug": "veracode", "category": "AppSec Intelligence"},
    {"name": "Aqua Security", "slug": "aquasecurity", "category": "Cloud Native Security"},
    {"name": "Sysdig", "slug": "sysdig", "category": "Container & Cloud Security"},
    {"name": "Lacework", "slug": "lacework", "category": "Cloud Security Platform"},
    {"name": "Orca Security", "slug": "orcasecurity", "category": "Agentless Cloud Security"},
    {"name": "Wiz", "slug": "wiz", "category": "Cloud Security Framework"},
    {"name": "Harness", "slug": "harness", "category": "Modern Software Delivery"},
    {"name": "Argo CD", "slug": "argocd", "category": "Declarative GitOps"},
    {"name": "Pulumi Corp", "slug": "pulumicorp", "category": "Cloud Engineering"},
    {"name": "Upbound", "slug": "upbound", "category": "Crossplane Cloud Control"},
    {"name": "Chainguard", "slug": "chainguard", "category": "Secure Software Supply Chain"},
    {"name": "Red Hat", "slug": "redhat", "category": "Open Source Enterprise Solutions"},
    {"name": "Canonical", "slug": "canonical", "category": "Ubuntu & Cloud Infrastructure"},
    {"name": "SUSE", "slug": "suse", "category": "Open Source Infrastructure"}
]

# 4. Lever Public API Targets (45 High-Growth Companies & Modern SaaS)
LEVER_SOURCES = [
    {"name": "Spotify", "slug": "spotify", "category": "Audio Streaming & Tech"},
    {"name": "Canva", "slug": "canva", "category": "Graphic Design Platform"},
    {"name": "Framer", "slug": "framer", "category": "Interactive Design Tools"},
    {"name": "ClearTax", "slug": "cleartax", "category": "Fintech & Tax Software"},
    {"name": "Instawork", "slug": "instawork", "category": "Flexible Work Marketplace"},
    {"name": "Netflix", "slug": "netflix", "category": "Streaming & Cloud Tech"},
    {"name": "Lyft", "slug": "lyft", "category": "Rideshare & Transportation"},
    {"name": "Palantir", "slug": "palantir", "category": "Data Systems & AI"},
    {"name": "Kraken", "slug": "kraken", "category": "Crypto Exchange & Web3"},
    {"name": "Yelp", "slug": "yelp", "category": "Local Search & Reviews"},
    {"name": "Webflow", "slug": "webflow", "category": "Visual CMS & Hosting"},
    {"name": "Buffer", "slug": "buffer", "category": "Social Media Toolkit"},
    {"name": "Sourcegraph", "slug": "sourcegraph", "category": "Code Intelligence & AI"},
    {"name": "Udemy", "slug": "udemy", "category": "Online Learning Marketplace"},
    {"name": "Coursera", "slug": "coursera", "category": "Online Education Platform"},
    {"name": "Pluralsight", "slug": "pluralsight", "category": "Tech Workforce Development"},
    {"name": "Skillshare", "slug": "skillshare", "category": "Online Learning Community"},
    {"name": "MasterClass", "slug": "masterclass", "category": "Streaming Education"},
    {"name": "Duolingo", "slug": "duolingo", "category": "Language Learning & AI"},
    {"name": "Codecademy", "slug": "codecademy", "category": "Interactive Coding Education"},
    {"name": "DataCamp", "slug": "datacamp", "category": "Data Science & AI Learning"},
    {"name": "Udacity", "slug": "udacity", "category": "Nanodegree Tech Programs"},
    {"name": "edX", "slug": "edx", "category": "Global Learning Platform"},
    {"name": "Chegg", "slug": "chegg", "category": "Student Learning Platform"},
    {"name": "Quizlet", "slug": "quizlet", "category": "AI Study Tools"},
    {"name": "Grammarly", "slug": "grammarly", "category": "AI Writing Assistant"},
    {"name": "QuillBot", "slug": "quillbot", "category": "AI Paraphrasing & Writing"},
    {"name": "Roam Research", "slug": "roam", "category": "Networked Thought & PKM"},
    {"name": "Obsidian", "slug": "obsidian", "category": "Knowledge Base Software"},
    {"name": "Superhuman", "slug": "superhuman", "category": "Fast Email Experience"},
    {"name": "Front", "slug": "front", "category": "Customer Operations Platform"},
    {"name": "Readwise", "slug": "readwise", "category": "Reading & Highlighting Software"},
    {"name": "Pocket", "slug": "pocket", "category": "Content Curation Platform"},
    {"name": "Instapaper", "slug": "instapaper", "category": "Save & Read Later"},
    {"name": "Feedly", "slug": "feedly", "category": "AI News & RSS Reader"},
    {"name": "Inoreader", "slug": "inoreader", "category": "Content Curation & RSS"},
    {"name": "Replit Lever", "slug": "replit", "category": "Collaborative Development"},
    {"name": "Zapier Lever", "slug": "zapier", "category": "Workflow Automation"},
    {"name": "1Password", "slug": "1password", "category": "Password Security"},
    {"name": "Bitwarden", "slug": "bitwarden", "category": "Open Source Password Security"},
    {"name": "Auth0", "slug": "auth0", "category": "Identity Platform for Developers"},
    {"name": "Clerk", "slug": "clerk", "category": "Authentication for React & Next.js"},
    {"name": "Stytch", "slug": "stytch", "category": "Passwordless Auth Infrastructure"},
    {"name": "Ory", "slug": "ory", "category": "Open Source Identity Infrastructure"},
    {"name": "WorkOS", "slug": "workos", "category": "Enterprise Ready Features"}
]

# 5. Remote Tech Aggregator Endpoints & Direct Feed Streams (20 Specialized Streams)
REMOTE_AGGREGATOR_URLS = [
    # We Work Remotely Streams
    {"name": "WWR Fullstack", "url": "https://weworkremotely.com/categories/remote-full-stack-programming-jobs.rss", "type": "rss"},
    {"name": "WWR Frontend", "url": "https://weworkremotely.com/categories/remote-front-end-programming-jobs.rss", "type": "rss"},
    {"name": "WWR Backend", "url": "https://weworkremotely.com/categories/remote-back-end-programming-jobs.rss", "type": "rss"},
    {"name": "WWR DevOps", "url": "https://weworkremotely.com/categories/remote-devops-sysadmin-jobs.rss", "type": "rss"},
    {"name": "WWR Data & AI", "url": "https://weworkremotely.com/categories/remote-data-science-jobs.rss", "type": "rss"},
    {"name": "WWR Mobile", "url": "https://weworkremotely.com/categories/remote-mobile-app-development-jobs.rss", "type": "rss"},
    
    # Remotive Engineering Endpoints
    {"name": "Remotive Software Dev", "url": "https://remotive.com/api/remote-jobs?category=software-dev&limit=25", "type": "remotive"},
    {"name": "Remotive QA", "url": "https://remotive.com/api/remote-jobs?category=qa&limit=25", "type": "remotive"},
    {"name": "Remotive DevOps", "url": "https://remotive.com/api/remote-jobs?category=devops&limit=25", "type": "remotive"},
    {"name": "Remotive Data", "url": "https://remotive.com/api/remote-jobs?category=data&limit=25", "type": "remotive"},
    
    # RemoteOK Developer API
    {"name": "RemoteOK Dev", "url": "https://remoteok.com/api", "type": "remoteok"},
    
    # Jobicy Remote Engineering Feeds
    {"name": "Jobicy Engineering", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=engineering", "type": "jobicy"},
    {"name": "Jobicy Dev", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=dev", "type": "jobicy"},
    {"name": "Jobicy React", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=react", "type": "jobicy"},
    {"name": "Jobicy Python", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=python", "type": "jobicy"},
    {"name": "Jobicy JavaScript", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=javascript", "type": "jobicy"},
    {"name": "Jobicy Golang", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=golang", "type": "jobicy"},
    {"name": "Jobicy Fullstack", "url": "https://jobicy.com/api/v2/remote-jobs?count=25&tag=fullstack", "type": "jobicy"},
    
    # Arbeitnow European & Global Remote API
    {"name": "Arbeitnow Remote", "url": "https://www.arbeitnow.com/api/job-board-api", "type": "arbeitnow"}
]

# Feeds and API helper structures
WWR_FEEDS = [item["url"] for item in REMOTE_AGGREGATOR_URLS if item["type"] == "rss"]

AGGREGATOR_APIS = {
    "remotive": [item["url"] for item in REMOTE_AGGREGATOR_URLS if item["type"] == "remotive"],
    "remoteok": "https://remoteok.com/api",
    "jobicy": [item["url"] for item in REMOTE_AGGREGATOR_URLS if item["type"] == "jobicy"],
    "arbeitnow": "https://www.arbeitnow.com/api/job-board-api"
}

TOTAL_SOURCES_COUNT = (
    len(INTERNSHALA_URLS) +
    len(ASHBY_SOURCES) +
    len(GREENHOUSE_SOURCES) +
    len(LEVER_SOURCES) +
    len(REMOTE_AGGREGATOR_URLS)
)
